# Selected via `mkosi --profile=comet build`. Builds Mechanix OS for real Mecha Comet hardware

[Distribution]
Architecture=arm64

[Content]
Devicetrees=freescale/imx8mp-mecha-comet.dtb
ExtraTrees=mkosi.extra.comet
