# Core OS: comps groups, init/login stack, and general CLI tools.

[Content]
Packages=
    @core
    @networkmanager-submodules
    @standard
    htop
    nano
    NetworkManager-config-connectivity-fedora
    nss
    openssh-server
    openssl
    seatd
    sudo
    systemd
    systemd-boot-unsigned
    systemd-pam
    systemd-udev
    xdg-user-dirs
