# Mecha Comet (imx8mp) hardware enablement

[Match]
Profiles=comet

[Content]
Packages=
    bluez
    bluez-obexd
    can-utils
    cpufrequtils
    evtest
    i2c-tools
    libcamera
    libcamera-devel
    libgpiod-utils
    linux-firmware-imx-sdma
    mesa-demos
    upower
    usbutils
    # SSH over USB
    dnsmasq
    # USB mode manager
    usb-signaller
    # Custom packages
    nxp-w61x-firmware
    kernel-core-7.1.5-0.mecha.*
    kernel-modules-7.1.5-0.mecha.*
    kernel-modules-core-7.1.5-0.mecha.*
    kernel-modules-extra-7.1.5-0.mecha.*
