# Graphical stack

[Content]
Packages=
    @base-graphical
    alacritty
    greetd
    gsettings-desktop-schemas
    gnome-keyring
    gnome-keyring-pam
    mutter
    phoc
    phosh
    phosh-mobile-settings
    weston-demo
    xorg-x11-server-Xwayland
