# Graphical stack

[Content]
Packages=
    @base-graphical
    alacritty
    fontawesome-fonts-all
    greetd
    gsettings-desktop-schemas
    gnome-keyring
    gnome-keyring-pam 
    jetbrains-mono-fonts
    mutter
    weston-demo
    xorg-x11-server-Xwayland
