# Mechanix app suite and its supporting services.

[Match]
Profiles=comet

[Content]
Packages=
    mechanix-calculator
    mechanix-camera
    mechanix-clock
    mechanix-contacts
    mechanix-dialer
    mechanix-files
    mechanix-keyboard
    mechanix-lockscreen
    mechanix-music
    mechanix-notes
    mechanix-settings
    mechanix-system-service
    mechanix-terminal
    mechanix-wallpapers
    mxconf
    mxsearch
    session_service
