hostname: mecha-comet-m
locale:
  timezone: America/Los_Angeles
  lang: en-US.UTF-8
user:
  name: mecha
  password: mecha
  is_password_expired: true
ssh:
  user_ca:
  host_ca:
  authorized_keys: []
  is_password_authentication_disabled: false
debian:
  version: 13
  name: trixie
apt:
  sources:
    - url: http://pkg.mecha.so/debian pulp upload
      key: https://pub-a2f44c787cec4290833312e57fd59522.r2.dev/comet.asc
    - url: http://debian.mecha.build apollo main
      key: null 
os-release:
  ID: mechanix
  ID_LIKE:
    - debian
  NAME: Mechanix
  VERSION: "25.10.0 LTS (Apollo)"
  VERSION_ID: "25.10"
  VERSION_CODENAME: Apollo
  PRETTY_NAME: "Mechanix 25.10 LTS"
  HOME_URL: "https://mecha.so/"
  SUPPORT_URL: "https://forum.mecha.so/"
  BUG_REPORT_URL: "https://forum.mecha.so/"

keyboard-config:
  layout: "us"
  model: "pc1067"
  variant: ""
  options: ""
  toggle: "No toggling"

#  make this as relative path
packages-path: ./include/
scripts-path: ./../../uboot/include
media-files: ./include/splash/
firmware-files: ./include/packages/firmware
include-path: ./include
