#!/bin/sh -e

if [ "$1" = "prereqs" ]; then exit 0; fi
. /usr/share/initramfs-tools/hook-functions

cp /lib/firmware/LICENCE.broadcom_bcm43xx $DESTDIR/lib/firmware/LICENCE.broadcom_bcm43xx
cp /lib/firmware/regulatory.db $DESTDIR/lib/firmware
cp /lib/firmware/brcm/brcmfmac43455-sdio.AW-CM256SM.txt $DESTDIR/lib/firmware/brcm
cp /lib/firmware/brcm/brcmfmac43455-sdio.txt $DESTDIR/lib/firmware/brcm
cp /lib/firmware/regulatory.db.p7s $DESTDIR/lib/firmware